backend:
  name: git-gateway
  branch: main

media_folder: src/images # Corrected from 'srt/images' to 'src/images'
public_folder: /images

collections:
  - name: 'configurations'
    label: 'Site Configurations'
    files:
      - name: 'networks'
        label: 'Networks Supported Banner'
        file: 'src/data/networks.json'
        fields:
          - { label: 'Number of Networks', name: 'number', widget: 'string' }
          - label: 'Networks'
            name: 'networks'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'src', widget: 'image' }
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Ticker', name: 'ticker', widget: 'string' }
          - { label: 'Button Text', name: 'buttonText', widget: 'string' }
      - name: 'coinBanner'
        label: 'Coin Banner'
        file: 'src/data/coinBanner.json'
        fields:
          - { label: 'Background Image', name: 'backgroundImage', widget: 'image' }
          - { label: 'Coin Logo', name: 'coinLogo', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text 1', name: 'text1', widget: 'string' }
          - { label: 'Text 2', name: 'text2', widget: 'string' }
          - { label: 'Logo Size', name: 'logoSize', widget: 'string' }
          - { label: 'Height', name: 'height', widget: 'string' }
      - name: 'imageCompactBanner1'
        label: 'Image Compact Banner 1'
        file: 'src/data/imageCompactBanner1.json'
        fields:
          - { label: 'Image', name: 'imgSrc', widget: 'image' }
          - { label: 'Coin Logo', name: 'coinLogoSrc', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text', name: 'text', widget: 'string' }
      - name: 'imageCompactBanner2'
        label: 'Image Compact Banner 2'
        file: 'src/data/imageCompactBanner2.json'
        fields:
          - { label: 'Image', name: 'imgSrc', widget: 'image' }
          - { label: 'Coin Logo', name: 'coinLogoSrc', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text', name: 'text', widget: 'string' }
          - { label: 'Reverse Layout', name: 'reverse', widget: 'boolean', required: false }
      - name: 'imageCompactBanner3'
        label: 'Image Compact Banner 3'
        file: 'src/data/imageCompactBanner3.json'
        fields:
          - { label: 'Image', name: 'imgSrc', widget: 'image' }
          - { label: 'Coin Logo', name: 'coinLogoSrc', widget: 'image' }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Text', name: 'text', widget: 'string' }
      - name: 'centeredTitleWithImage'
        label: 'Centered Title With Image'
        file: 'src/data/centeredTitleWithImage.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Image', name: 'imgSrc', widget: 'image' }
      - name: 'tripleDottedImageHeaderGroup'
        label: 'Triple Dotted Image Header Group'
        file: 'src/data/tripleDottedImageHeaderGroup.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'imgSrc', widget: 'image' }
              - { label: 'Header', name: 'header', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'string' }
